version: 2
updates:
  - package-ecosystem: "npm"
    directory: "ch9_release/src/Tailwind.Traders.Web/ClientApp"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget"
    directory: "ch9_release/src/Tailwind.Traders.Web"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "ch9_release/src/Tailwind.Traders.Web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
