# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE
  template:
    metadata:
      labels:
        app: $IMAGE
    spec:
      containers:
      - name: $IMAGE
        image: $GKE_REGION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
