name: Deploy-Azure

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3    

    - name: Install dependencies in client app
      working-directory: ch9_release/src/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: ch9_release/src/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o publish
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ch9_release/src/Tailwind.Traders.Web/publish
   
  Deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: Build
    
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      
    - uses: actions/download-artifact@v2
      with:
        name: website
    
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: bigpicture
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: website
