name: SBOM

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ch8_packages/docker
      
    - name: Anchore SBOM Action
      uses: anchore/sbom-action@v0.6.0
