name: Starter Workflow

on:
  # Webhook events
  push:
    branches: 
      - main
  issues:
    types: [opened, edited, milestoned]
    
  # Scheduled events
  schedule:
    - cron: '*/15 * * * *'
    - cron: '0 9-17 * * *'
    - cron: '11 11 * * 5'

  # Manual events
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
        default: '/home'
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 


  # 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      - run: echo "🏠 drive is `${{ github.event.inputs.homedrive }}`."
